name: build

on:
  push:
    paths-ignore: 
      - README.md
  pull_request:
    paths-ignore: 
      - README.md

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ matrix.nim-version}}

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ matrix.nim-version}}-${{ hashFiles('*.nimble') }}

    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1.3.2
      # with:
      #   nim-version: ${{ matrix.nim-version }}

    - name: Install Packages
      run: nimble install -d -y
    - name: install crown cli
      run: nimble install https://github.com/bung87/crowncli
    - name: build
      run: nimble macos
    - uses: actions/upload-artifact@v2
      with:
        name: debug version app
        path: build/macos/Debug/crown_excel.app
    - name: create dmg
      run: >
        npm install --global create-dmg
        create-dmg 'build/macos/Debug/crown_excel.app' Build/Releases
        ls Build/Releases
    - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Build/Releases/crown_excel.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}